export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCEED = 'GET_USERS_SUCCEED';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCEED = 'CREATE_USER_SUCCEED';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCEED = 'DELETE_USER_SUCCEED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCEED = 'UPDATE_USER_SUCCEED';